plugins { id 'com.android.application' }

android {
    namespace 'kz.almas.remote'
    compileSdk 35

    defaultConfig {
        applicationId 'kz.almas.remote'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '2.3'
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            // Temporary project signing: optimized/non-debuggable APK while keeping install simple.
            signingConfig signingConfigs.debug
        }
    }
}
